Repository pabmejbui/Acme-ANS, pull requests merged in 2025-04, with the labels that each got.

#573 Task 083 - Operations by managers on their legs #426
  src/main/java/acme/constraints/flights/FlightNumberValidator.java
  src/main/java/acme/constraints/flights/LegValidator.java
  src/main/java/acme/constraints/flights/ValidFlightNumber.java
  src/main/java/acme/constraints/flights/ValidLeg.java
  src/main/java/acme/entities/flights/FlightRepository.java
  src/main/java/acme/features/manager/flight/ManagerFlightDeleteService.java
  src/main/java/acme/features/manager/flight/ManagerFlightPublishService.java
  src/main/java/acme/features/manager/flight/ManagerFlightShowService.java
  src/main/java/acme/features/manager/leg/ManagerLegController.java
  src/main/java/acme/features/manager/leg/ManagerLegCreateService.java
  src/main/java/acme/features/manager/leg/ManagerLegDeleteService.java
  src/main/java/acme/features/manager/leg/ManagerLegListService.java
  src/main/java/acme/features/manager/leg/ManagerLegPublishService.java
  src/main/java/acme/features/manager/leg/ManagerLegRepository.java
  src/main/java/acme/features/manager/leg/ManagerLegShowService.java
  src/main/java/acme/features/manager/leg/ManagerLegUpdateService.java
  src/main/resources/WEB-INF/data/initial/DUMMY.txt
  src/main/resources/WEB-INF/data/sample/leg.csv
  src/main/resources/WEB-INF/data/sample/manager.csv
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/manager/flight/form.jsp
  src/main/resources/WEB-INF/views/manager/flight/messages-en.i18n
  src/main/resources/WEB-INF/views/manager/flight/messages-es.i18n
  src/main/resources/WEB-INF/views/manager/leg/form.jsp
  src/main/resources/WEB-INF/views/manager/leg/list.jsp
  src/main/resources/WEB-INF/views/manager/leg/messages-en.i18n
  src/main/resources/WEB-INF/views/manager/leg/messages-es.i18n
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
Labels: enhancement, Individual, mandatory

#576 feat(student1): Task 085 - Operations by anonymous on user accounts #430
  src/main/java/acme/features/authenticated/manager/AuthenticatedManagerController.java
  src/main/java/acme/features/authenticated/manager/AuthenticatedManagerCreateService.java
  src/main/java/acme/features/authenticated/manager/AuthenticatedManagerRepository.java
  src/main/java/acme/features/authenticated/manager/AuthenticatedManagerUpdateService.java
  src/main/resources/WEB-INF/views/authenticated/manager/form.jsp
  src/main/resources/WEB-INF/views/authenticated/manager/messages-en.i18n
  src/main/resources/WEB-INF/views/authenticated/manager/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, Individual, suplementary-I

#577 feat(student1): Task 087 - Operations by any principals on flights #434
  src/main/java/acme/features/any/flight/AnyFlightController.java
  src/main/java/acme/features/any/flight/AnyFlightListService.java
  src/main/java/acme/features/any/flight/AnyFlightRepository.java
  src/main/java/acme/features/any/flight/AnyFlightShowService.java
  src/main/resources/WEB-INF/views/administrator/airline/messages-en.i18n
  src/main/resources/WEB-INF/views/any/flight/form.jsp
  src/main/resources/WEB-INF/views/any/flight/list.jsp
  src/main/resources/WEB-INF/views/any/flight/messages-en.i18n
  src/main/resources/WEB-INF/views/any/flight/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, Individual, suplementary-I

#578 fix(Student3): fixing
  reports/Student #3/03 - Requirements - Student #3.docx
  reports/Student #3/D02/D02 - Student#3 - Planning and progress report.docx
  reports/Student #3/D02/D02 - Student3- UML.pdf
  reports/Student #3/D02/D02 - Student3- UML.uxf
  reports/Student #3/D02/UML/D02 - Student3 - UML.pdf
  reports/Student #3/D02/UML/D02 - Student3- UML.uxf
  src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentPublishService.java
  src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentUpdateService.java
  src/main/resources/WEB-INF/views/flight-crew-member/flight-assignment/form.jsp
Labels: bug, enhancement, Individual, mandatory

#580 feat(student1): Task 88 - Operations by managers on manager dashboards #436
  src/main/java/acme/features/manager/managerDashboard/ManagerDashboardController.java
  src/main/java/acme/features/manager/managerDashboard/ManagerDashboardRepository.java
  src/main/java/acme/features/manager/managerDashboard/ManagerDashboardShowService.java
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/manager/manager-dashboard/form.jsp
  src/main/resources/WEB-INF/views/manager/manager-dashboard/messages-en.i18n
  src/main/resources/WEB-INF/views/manager/manager-dashboard/messages-es.i18n
Labels: enhancement, Individual, suplementary-I

#582 Task 097 operations by anonymous principals on user accounts
  .settings/org.eclipse.wst.common.component
  src/main/java/acme/constraints/ValidIdentifier.java
  src/main/java/acme/constraints/customer/CustomerValidator.java
  src/main/java/acme/features/authenticated/customer/AuthenticatedCustomerController.java
  src/main/java/acme/features/authenticated/customer/AuthenticatedCustomerCreateService.java
  src/main/java/acme/features/authenticated/customer/AuthenticatedCustomerRepository.java
  src/main/java/acme/features/authenticated/customer/AuthenticatedCustomerUpdateService.java
  src/main/resources/WEB-INF/data/sample/customer.csv
  src/main/resources/WEB-INF/views/authenticated/customer/form.jsp
  src/main/resources/WEB-INF/views/authenticated/customer/messages-en.i18n
  src/main/resources/WEB-INF/views/authenticated/customer/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
Labels: enhancement, Individual, suplementary-I

#583 Task 099 operations by administrators on bookings
  src/main/java/acme/features/administrator/booking/AdministratorBookingController.java
  src/main/java/acme/features/administrator/booking/AdministratorBookingListService.java
  src/main/java/acme/features/administrator/booking/AdministratorBookingRepository.java
  src/main/java/acme/features/administrator/booking/AdministratorBookingShowService.java
  src/main/resources/WEB-INF/views/administrator/booking/form.jsp
  src/main/resources/WEB-INF/views/administrator/booking/list.jsp
  src/main/resources/WEB-INF/views/administrator/booking/messages-en.i18n
  src/main/resources/WEB-INF/views/administrator/booking/messages-es.i18n
  src/main/resources/WEB-INF/views/authenticated/customer/messages-en.i18n
  src/main/resources/WEB-INF/views/authenticated/customer/messages-es.i18n
  src/main/resources/WEB-INF/views/customer/booking/messages-en.i18n
  src/main/resources/WEB-INF/views/customer/booking/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, Individual, suplementary-I

#584 Task 107 operations by assistance agents on claim
  src/main/java/acme/entities/aircrafts/AircraftRepository.java
  src/main/java/acme/entities/claims/Claim.java
  src/main/java/acme/entities/claims/ClaimIndicator.java
  src/main/java/acme/entities/claims/ClaimRepository.java
  src/main/java/acme/entities/trackingLogs/TrackingLog.java
  src/main/java/acme/entities/trackingLogs/TrackingLogStatus.java
  src/main/java/acme/features/administrator/aircraft/AdministratorAircraftController.java
  src/main/java/acme/features/administrator/aircraft/AdministratorAircraftCreateService.java
  src/main/java/acme/features/administrator/aircraft/AdministratorAircraftListService.java
  src/main/java/acme/features/administrator/aircraft/AdministratorAircraftRepository.java
  src/main/java/acme/features/administrator/aircraft/AdministratorAircraftShowService.java
  src/main/java/acme/features/administrator/aircraft/AdministratorAircraftUpdateService.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimController.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimCreateService.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimDeleteService.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimListService.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimListUndergoingService.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimPublishService.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimRepository.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimShowService.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimUpdateService.java
  src/main/java/acme/forms/AssistanceAgentDashboards.java
  src/main/java/acme/realms/assistanceAgent/AssistanceAgent.java
  src/main/java/acme/realms/assistanceAgent/AssistanceAgentRepository.java
  src/main/resources/WEB-INF/data/sample/claim.csv
  src/main/resources/WEB-INF/data/sample/trackingLog.csv
  src/main/resources/WEB-INF/views/administrator/aircraft/form.jsp
  src/main/resources/WEB-INF/views/administrator/aircraft/list.jsp
  src/main/resources/WEB-INF/views/administrator/aircraft/messages-en.i18n
  src/main/resources/WEB-INF/views/administrator/aircraft/messages-es.i18n
  src/main/resources/WEB-INF/views/assistance-agent/claim/form.jsp
  src/main/resources/WEB-INF/views/assistance-agent/claim/list.jsp
  src/main/resources/WEB-INF/views/assistance-agent/claim/messages-en.i18n
  src/main/resources/WEB-INF/views/assistance-agent/claim/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, Individual

#589 fix(student1): Task 143 - Done #586
  .settings/org.eclipse.wst.common.component
  src/main/java/acme/constraints/aircraft/AircraftValidator.java
  src/main/java/acme/constraints/aircraft/ValidAircraft.java
  src/main/java/acme/constraints/airline/AirlineValidator.java
  src/main/java/acme/constraints/airline/ValidAirline.java
  src/main/java/acme/constraints/airline/ValidIataCode.java
  src/main/java/acme/constraints/flights/FlightValidator.java
  src/main/java/acme/constraints/flights/ValidFlight.java
  src/main/java/acme/constraints/manager/ManagerValidator.java
  src/main/java/acme/entities/aircrafts/Aircraft.java
  src/main/java/acme/entities/airlines/Airline.java
  src/main/java/acme/entities/airlines/AirlineRepository.java
  src/main/java/acme/entities/flights/Flight.java
  src/main/java/acme/entities/flights/FlightRepository.java
  src/main/java/acme/features/administrator/aircraft/AdministratorAircraftCreateService.java
  src/main/java/acme/features/administrator/aircraft/AdministratorAircraftListService.java
  src/main/java/acme/features/administrator/aircraft/AdministratorAircraftRepository.java
  src/main/java/acme/features/administrator/aircraft/AdministratorAircraftShowService.java
  src/main/java/acme/features/administrator/aircraft/AdministratorAircraftUpdateService.java
  src/main/java/acme/features/authenticated/manager/AuthenticatedManagerController.java
  src/main/java/acme/features/authenticated/manager/AuthenticatedManagerCreateService.java
  src/main/java/acme/features/authenticated/manager/AuthenticatedManagerRepository.java
  src/main/java/acme/features/authenticated/manager/AuthenticatedManagerUpdateService.java
  src/main/java/acme/features/manager/flight/ManagerFlightController.java
  src/main/java/acme/features/manager/flight/ManagerFlightCreateService.java
  src/main/java/acme/features/manager/flight/ManagerFlightDeleteService.java
  src/main/java/acme/features/manager/flight/ManagerFlightListService.java
  src/main/java/acme/features/manager/flight/ManagerFlightPublishService.java
  src/main/java/acme/features/manager/flight/ManagerFlightShowService.java
  src/main/java/acme/features/manager/flight/ManagerFlightUpdateService.java
  src/main/java/acme/features/manager/leg/ManagerLegController.java
  src/main/java/acme/features/manager/leg/ManagerLegCreateService.java
  src/main/java/acme/features/manager/leg/ManagerLegDeleteService.java
  src/main/java/acme/features/manager/leg/ManagerLegListService.java
  src/main/java/acme/features/manager/leg/ManagerLegPublishService.java
  src/main/java/acme/features/manager/leg/ManagerLegShowService.java
  src/main/java/acme/features/manager/leg/ManagerLegUpdateService.java
  src/main/java/acme/features/manager/managerDashboard/ManagerDashboardController.java
  src/main/java/acme/features/manager/managerDashboard/ManagerDashboardRepository.java
  src/main/java/acme/features/manager/managerDashboard/ManagerDashboardShowService.java
  src/main/java/acme/realms/manager/Manager.java
  src/main/java/acme/realms/manager/ManagerRepository.java
  src/main/resources/WEB-INF/views/authenticated/manager/form.jsp
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
Labels: bug, enhancement, Individual

#591 Task 065 operations by administrators on airports
  src/main/java/acme/features/administrator/airport/AdministratorAirportController.java
  src/main/java/acme/features/administrator/airport/AdministratorAirportCreateService.java
  src/main/java/acme/features/administrator/airport/AdministratorAirportListService.java
  src/main/java/acme/features/administrator/airport/AdministratorAirportRepository.java
  src/main/java/acme/features/administrator/airport/AdministratorAirportShowService.java
  src/main/java/acme/features/administrator/airport/AdministratorAirportUpdateService.java
  src/main/resources/WEB-INF/views/administrator/airport/form.jsp
  src/main/resources/WEB-INF/views/administrator/airport/list.jsp
  src/main/resources/WEB-INF/views/administrator/airport/messages-en.i18n
  src/main/resources/WEB-INF/views/administrator/airport/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, Group, mandatory

#593 feat(student1): requirements student1
  reports/Student #1/01 - Requirements - Student #1.docx
Labels: documentation, Individual, mandatory

#595 doc(Student4): PlanningProgress Report Added
  reports/Student #4/D03/D03 - Student#4 - Planning and progress report.docx
  src/main/resources/WEB-INF/data/sample/claim.csv
Labels: bug, documentation
