Repository pabmejbui/Acme-ANS, pull requests merged in 2025-06, with the labels that each got.

#749 Task 199 - Lack of data in Student1 csvs
  src/main/java/acme/constraints/flights/FlightNumberValidator.java
  src/main/java/acme/entities/flights/Flight.java
  src/main/java/acme/entities/flights/Leg.java
  src/main/java/acme/features/manager/leg/ManagerLegCreateService.java
  src/main/java/acme/features/manager/leg/ManagerLegShowService.java
  src/main/resources/WEB-INF/data/sample/aircraft.csv
  src/main/resources/WEB-INF/data/sample/airline.csv
  src/main/resources/WEB-INF/data/sample/airport.csv
  src/main/resources/WEB-INF/data/sample/flight.csv
  src/main/resources/WEB-INF/data/sample/leg.csv
Labels: bug, Individual, mandatory

#753 fix(student1): Task 199 - Lack of data in Student 1 entities csvs. #747
  src/main/java/acme/constraints/flights/FlightValidator.java
  src/main/java/acme/entities/flights/FlightRepository.java
  src/main/resources/WEB-INF/data/sample/activityLog.csv
  src/main/resources/WEB-INF/data/sample/aircraft.csv
  src/main/resources/WEB-INF/data/sample/leg.csv
Labels: bug, Individual, mandatory

#754 feat: improving csvs
  .project
  src/main/java/acme/constraints/flights/FlightValidator.java
  src/main/resources/WEB-INF/data/sample/booking.csv
  src/main/resources/WEB-INF/data/sample/bookingRecord.csv
  src/main/resources/WEB-INF/data/sample/customer.csv
  src/main/resources/WEB-INF/data/sample/passenger.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: enhancement, Individual, mandatory

#757 Task 203 update select flights
  src/main/java/acme/features/customer/booking/CustomerBookingCreateService.java
  src/main/java/acme/features/customer/booking/CustomerBookingDeleteService.java
  src/main/java/acme/features/customer/booking/CustomerBookingPublishService.java
  src/main/java/acme/features/customer/booking/CustomerBookingRepository.java
  src/main/java/acme/features/customer/booking/CustomerBookingShowService.java
  src/main/java/acme/features/customer/booking/CustomerBookingUpdateService.java
  src/main/resources/WEB-INF/data/sample/booking.csv
  src/main/resources/WEB-INF/views/customer/booking/form.jsp
  src/main/resources/WEB-INF/views/customer/booking/messages-en.i18n
  src/main/resources/WEB-INF/views/customer/booking/messages-es.i18n
Labels: enhancement, Individual, mandatory

#759 fix(student1): Task 199 - Lack of data in Student 1 entities csvs. #747
  src/main/resources/WEB-INF/data/sample/flight.csv
  src/main/resources/WEB-INF/data/sample/leg.csv
Labels: bug, Individual, mandatory

#761 Task 204 prevent duplicate passengers
  src/main/java/acme/features/customer/booking/CustomerBookingRepository.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerCreateService.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerPublishService.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerRepository.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerUpdateService.java
  src/main/resources/WEB-INF/data/sample/booking.csv
  src/main/resources/WEB-INF/data/sample/passenger.csv
  src/main/resources/WEB-INF/views/customer/passenger/messages-en.i18n
  src/main/resources/WEB-INF/views/customer/passenger/messages-es.i18n
Labels: enhancement, Individual, mandatory

#765 feat: customer recommendations done!
  src/main/java/acme/entities/recomendations/Recommendation.java
  src/main/java/acme/features/administrator/recommendation/AdministratorRecommendationInitialiseController.java
  src/main/java/acme/features/administrator/recommendation/AdministratorRecommendationRepository.java
  src/main/java/acme/features/customer/bookingRecord/CustomerBookingRecordRepository.java
  src/main/java/acme/features/customer/recomendation/CustomerRecommendationController.java
  src/main/java/acme/features/customer/recomendation/CustomerRecommendationListService.java
  src/main/java/acme/features/customer/recomendation/CustomerRecommendationRepository.java
  src/main/java/acme/features/customer/recomendation/CustomerRecommendationShowService.java
  src/main/resources/WEB-INF/data/sample/flight.csv
  src/main/resources/WEB-INF/views/customer/recommendation/form.jsp
  src/main/resources/WEB-INF/views/customer/recommendation/list.jsp
  src/main/resources/WEB-INF/views/customer/recommendation/messages-en.i18n
  src/main/resources/WEB-INF/views/customer/recommendation/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, Individual, suplementary-II

#769 fix(student1): Task 208 - Error in the student1 csvs logic #768
  src/main/resources/WEB-INF/data/sample/flight.csv
  src/main/resources/WEB-INF/data/sample/leg.csv
Labels: bug, Individual, mandatory

#785 Task 219 produce test suite for bookings
  src/main/java/acme/entities/bookings/Booking.java
  src/main/java/acme/features/customer/booking/CustomerBookingCreateService.java
  src/main/java/acme/realms/customer/Customer.java
  src/main/resources/WEB-INF/data/sample/booking.csv
  src/main/resources/WEB-INF/views/customer/booking/messages-en.i18n
  src/main/resources/WEB-INF/views/customer/booking/messages-es.i18n
  src/test/resources/customer/DUMMY.txt
  src/test/resources/customer/booking/CreateBooking.hack
  src/test/resources/customer/booking/CreateBooking.safe
  src/test/resources/customer/booking/DeleteBooking.hack
  src/test/resources/customer/booking/DeleteBooking.safe
  src/test/resources/customer/booking/ListBooking.hack
  src/test/resources/customer/booking/ListBooking.safe
  src/test/resources/customer/booking/PublishBooking.hack
  src/test/resources/customer/booking/PublishBooking.safe
  src/test/resources/customer/booking/ShowBooking.hack
  src/test/resources/customer/booking/ShowBooking.safe
  src/test/resources/customer/booking/UpdateBooking.hack
  src/test/resources/customer/booking/UpdateBooking.safe
Labels: testing, Individual, mandatory

#786 fix(Student3): Task 217 - Fixing the bugs in task 8 #778
  src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentCreateService.java
  src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentPublishService.java
  src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentRepository.java
  src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentShowService.java
  src/main/resources/WEB-INF/views/flight-crew-member/flight-assignment/form.jsp
Labels: bug, Individual, mandatory

#787 Task 220 produce test suite for passengers
  src/main/java/acme/features/customer/passenger/CustomerPassengerDeleteService.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerPublishService.java
  src/test/resources/customer/passenger/CreatePassenger.hack
  src/test/resources/customer/passenger/CreatePassenger.safe
  src/test/resources/customer/passenger/DeletePassenger.safe
  src/test/resources/customer/passenger/DeletePassengers.hack
  src/test/resources/customer/passenger/ListPassenger.hack
  src/test/resources/customer/passenger/ListPassenger.safe
  src/test/resources/customer/passenger/ListPassenger2.safe
  src/test/resources/customer/passenger/PublishPassenger.hack
  src/test/resources/customer/passenger/PublishPassenger.safe
  src/test/resources/customer/passenger/ShowPasenger.hack
  src/test/resources/customer/passenger/ShowPassenger.safe
  src/test/resources/customer/passenger/UpdatePassenger.hack
  src/test/resources/customer/passenger/UpdatePassenger.safe
Labels: testing, Individual, mandatory

#791 fix(student3): Task 204 - Lack of data in Student 3 entities csvs #758
  src/main/resources/WEB-INF/views/flight-crew-member/flight-assignment/form.jsp
Labels: bug, Individual, mandatory

#792 fix(Student3): Task 223 - Fixing the bugs in task 9 #790
  src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogCreateService.java
  src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogRepository.java
  src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogShowService.java
Labels: bug, Individual, mandatory
