Repository pabmejbui/Acme-ANS, pull requests merged in 2025-03, with the labels that each got.

#234 feat(student2): Task - 044 - Passenger entity done!
  src/main/java/acme/constraints/PassportValidator.java
  src/main/java/acme/constraints/ValidPassport.java
  src/main/java/acme/entities/passenger/Passenger.java
Labels: enhancement, Individual

#233 Task 042 customer data storage
  reports/Student #2/D02/UML-student-2.png
  reports/Student #2/D02/UML-student-2.uxf
  src/main/java/acme/components/DUMMY.txt
  src/main/java/acme/constraints/PhoneValidator.java
  src/main/java/acme/constraints/ValidPhone.java
  src/main/java/acme/entities/airlines/Airline.java
  src/main/java/acme/entities/airlines/AirlineType.java
  src/main/java/acme/entities/customers/Customer.java
Labels: enhancement, Individual

#235 feat(student1): Task 027 - UML Domain model #103
  reports/Student #1/D02/D02 - Student1 - UML.uxf
Labels: documentation, Individual

#239 Task 043 booking management
  src/main/java/acme/entities/bookings/Booking.java
  src/main/java/acme/entities/bookings/TravelClass.java
  src/main/java/acme/entities/customers/Customer.java
  src/main/java/acme/entities/services/Service.java
Labels: enhancement, Individual

#240 Task 045 sample test data
  src/main/java/acme/entities/customers/Customer.java
  src/main/resources/WEB-INF/data/sample/customer.csv
Labels: enhancement, Individual

#242 feat(group,student1): This pull request contains many tasks from student1 and group requirements
  src/main/java/acme/constraints/PhoneValidator.java
  src/main/java/acme/constraints/manager/ManagerValidator.java
  src/main/java/acme/constraints/manager/ValidManager.java
  src/main/java/acme/entities/airlines/Airline.java
  src/main/java/acme/realms/Manager.java
  src/main/resources/WEB-INF/data/sample/airline.csv
  src/main/resources/WEB-INF/data/sample/manager.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
Labels: bug, enhancement, Group, Individual

#243 fix(student2): fixing some problems with csv keys/ changed AbstractRole
  src/main/java/acme/entities/bookings/Booking.java
  src/main/java/acme/realms/Customer.java
  src/main/resources/WEB-INF/data/sample/customer.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: bug, Individual

#245 fix(student2): review done!!
  .gitignore
  src/main/java/acme/constraints/customer/CustomerValidator.java
  src/main/java/acme/constraints/customer/ValidCustomer.java
  src/main/java/acme/realms/Customer.java
  src/main/resources/WEB-INF/data/sample/customer.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
  src/main/resources/WEB-INF/views/authenticated/consumer/messages-en.i18n
  src/main/resources/WEB-INF/views/authenticated/consumer/messages-es.i18n
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
Labels: bug, Individual

#238 Task 009 flight assignment entity
  src/main/java/acme/entities/flightAssignment/AssignmentStatus.java
  src/main/java/acme/entities/flightAssignment/DutyType.java
  src/main/java/acme/entities/flightAssignment/FlightAssignment.java
Labels: enhancement, Individual

#237 Task 010 flight crew members entity
  src/main/java/acme/entities/flightCrewMembers/AvailabilityStatus.java
  src/main/java/acme/entities/flightCrewMembers/FlightCrewMember.java
Labels: enhancement, Individual

#236 Task 008 activity log entity
  src/main/java/acme/entities/activityLog/ActivityLog.java
Labels: enhancement, Individual

#247 fix(student2): testing requirements done!
  src/main/java/acme/entities/bookings/Booking.java
  src/main/java/acme/entities/bookings/TravelClass.java
  src/main/resources/WEB-INF/data/sample/booking.csv
  src/main/resources/WEB-INF/data/sample/passenger.csv
Labels: bug, Individual, mandatory

#248 fix(Student3): Some clasess fixed.
  src/main/java/acme/entities/flightAssignment/FlightAssignment.java
  src/main/java/acme/realms/flightCrewMembers/AvailabilityStatus.java
  src/main/java/acme/realms/flightCrewMembers/FlightCrewMember.java
  src/main/resources/WEB-INF/data/sample/flightCrewMember.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: enhancement, Individual, mandatory

#251 feat(student1): Task 022 - Flight entity #98
  src/main/java/acme/entities/activityLog/ActivityLog.java
  src/main/java/acme/entities/flightAssignment/FlightAssignment.java
  src/main/java/acme/entities/flights/Flight.java
  src/main/java/acme/entities/flights/FlightRepository.java
  src/main/java/acme/entities/flights/FlightService.java
  src/main/java/acme/entities/flights/Indication.java
  src/main/resources/WEB-INF/data/sample/flight.csv
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
Labels: enhancement, Individual

#252 feat(student1): Task 023 - Leg Entity #99
  src/main/java/acme/constraints/flights/FlightNumberValidator.java
  src/main/java/acme/constraints/flights/LegValidator.java
  src/main/java/acme/constraints/flights/ValidFlightNumber.java
  src/main/java/acme/constraints/flights/ValidLeg.java
  src/main/java/acme/entities/flightAssignment/FlightAssignment.java
  src/main/java/acme/entities/flights/Leg.java
  src/main/java/acme/entities/flights/LegStatus.java
Labels: enhancement, Individual

#254 fix(Student3):fix ejecution errors
  src/main/resources/WEB-INF/data/sample/flightCrewMember.csv
Labels: bug, Individual

#256 fix(Student3): Fixing relationship Activity Log.
  src/main/java/acme/entities/activityLog/ActivityLog.java
Labels: bug, Individual

#258 Task 059/R1 - Aircraft entity review #257
  src/main/java/acme/entities/aircrafts/Aircraft.java
  src/main/java/acme/entities/aircrafts/AircraftStatus.java
  src/main/java/acme/entities/flights/Leg.java
  src/main/resources/WEB-INF/data/sample/aircraft.csv
Labels: bug, enhancement, Group

#259 feat(student1): Task 026 - Manager dashboard #102
  src/main/java/acme/entities/activityLog/ActivityLog.java
  src/main/java/acme/forms/ManagerDashboard.java
Labels: enhancement, Individual

#262 fix(student1): Task 027/R1 - UML Domain Model fixed #260
  reports/Student #1/D02/D02 - Student1 - UML.pdf
  reports/Student #1/D02/D02 - Student1 - UML.uxf
Labels: bug, documentation

#264 fix(student2): change some syntax errors
  reports/Student #2/D02/D02-Student2-UML.uxf
  reports/Student #2/D02/UML-student-2.png
  reports/Student #2/D02/UML-student-2.uxf
Labels: documentation, enhancement, Individual, suplementary-I

#265 fix(Group): Task -060- R1 Service Entity
  src/main/java/acme/constraints/PromoCodeValidator.java
  src/main/java/acme/constraints/ValidPromoCode.java
  src/main/java/acme/entities/services/Service.java
  src/main/resources/WEB-INF/data/sample/service.csv
Labels: bug, enhancement, Group, mandatory

#266 feat(Student3):Task-007-SampleDataFlightCrewMember
  src/main/java/acme/realms/flightCrewMembers/FlightCrewMember.java
  src/main/resources/WEB-INF/data/sample/flightCrewMember.csv
Labels: enhancement, Individual, mandatory

#267 feat(Student3):Task054-AdministratorDashboards-done
  src/main/java/acme/forms/AdministratorDashboard.java
Labels: enhancement, Group, mandatory

#269 feat(Student3):FlightCrewMemberDashboard
  src/main/java/acme/forms/FlightCrewMemberDashboard.java
Labels: enhancement, Individual, suplementary-I

#275 fix(student1): Task 027/R2 UML fixed #274
  reports/Student #1/D02/D02 - Student1 - UML.pdf
  reports/Student #1/D02/D02 - Student1 - UML.uxf
Labels: bug, documentation, Individual

#271 feat(group): Task 058 completed
  src/main/java/acme/entities/airports/Airport.java
  src/main/resources/WEB-INF/data/sample/airport.csv
Labels: enhancement, Group, mandatory

#281 fix(group): Task 063/R1 - Airline entity fixed #279
  src/main/java/acme/entities/airlines/Airline.java
Labels: bug, enhancement, Group

#282 fix(group): Task 063/R1 - Airline entity fixed #279
  src/main/java/acme/entities/airlines/Airline.java
Labels: bug, enhancement, Group

#287 fix(stundet2): adding draftMode and Change TIMESTAMP type
  reports/Student #2/D02/D02-Student2-UML.uxf
  src/main/java/acme/entities/passenger/Passenger.java
  src/main/resources/WEB-INF/data/sample/passenger.csv
Labels: bug, enhancement, Individual, mandatory

#276 feat(group): Task 031 - Review Entity
  src/main/java/acme/entities/reviews/Review.java
  src/main/resources/WEB-INF/data/sample/review.csv
Labels: enhancement, Group, mandatory

#268 feat(Student4): Task 016 - UML Domain Model
  reports/Student #4/D02/D02 - Student4 - UML.uxf
Labels: enhancement, Individual, mandatory

#272 feat(Student4): Task 011 - Assistance Agent Entity
  src/main/java/acme/entities/assistanceAgents/AssistanceAgent.java
Labels: enhancement, Individual, mandatory

#286 feat(student4): Task 018 - Tracking Logs entity
  src/main/java/acme/entities/trackingLogs/Resolution.java
  src/main/java/acme/entities/trackingLogs/TrackingLog.java
Labels: enhancement, Individual, mandatory

#280 feat(student4): Task 014 - Claim entity
  src/main/java/acme/entities/claims/Claim.java
  src/main/java/acme/entities/claims/ClaimType.java
  src/main/java/acme/entities/trackingLog/Resolution.java
Labels: enhancement, Individual, mandatory

#288 fix(student2): draftMode and csv added!
  reports/Student #2/D02/D02-Student2-UML.uxf
  src/main/java/acme/entities/bookings/Booking.java
  src/main/resources/WEB-INF/data/sample/booking.csv
Labels: bug, enhancement, Individual, mandatory

#285 fix(group): Task 059/R2 - Aircraft entity fixed #284
  src/main/java/acme/entities/aircrafts/Aircraft.java
  src/main/java/acme/entities/airlines/Airline.java
Labels: bug, enhancement, Group

#291 fix(student1): Task 022/R1 - Flight fixes #290
  src/main/java/acme/constraints/flights/FlightNumberValidator.java
  src/main/java/acme/entities/claims/Claim.java
  src/main/java/acme/entities/flights/FlightService.java
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
Labels: bug, enhancement, Individual

#289 feat(group): Task 053 - System Configuration #127
  src/main/java/acme/configuration/SystemConfiguration.java
  src/main/java/acme/constraints/configuration/AcceptedCurrenciesValidator.java
  src/main/java/acme/constraints/configuration/CurrencyValidator.java
  src/main/java/acme/constraints/configuration/ValidAcceptedCurrencies.java
  src/main/java/acme/constraints/configuration/ValidCurrency.java
  src/main/resources/WEB-INF/data/initial/systemConfiguration.csv
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
Labels: enhancement, Group

#293 feat(student1): Task 023/R1 - Leg entity #292
  src/main/resources/WEB-INF/data/sample/leg.csv
Labels: enhancement, Individual

#283 fix(student2): draftMode added
  src/main/java/acme/entities/services/Service.java
  src/main/resources/WEB-INF/data/sample/service.csv
Labels: bug, enhancement, Group, mandatory

#294 feat(student5): Task 038 - Technician Entity
  src/main/java/acme/constraints/LicenseValidator.java
  src/main/java/acme/constraints/ValidLicense.java
  src/main/java/acme/realms/Technician.java
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
Labels: enhancement, Individual, mandatory

#295 feat(student5): Task 041 - Maintenance Records Entity
  src/main/java/acme/entities/maintenanceRecords/MaintenanceRecord.java
  src/main/java/acme/entities/maintenanceRecords/Status.java
Labels: enhancement, Individual, mandatory

#296 feat(Group) - Task 051 administrator sample data
  src/main/resources/WEB-INF/data/initial/DUMMY.txt
  src/main/resources/WEB-INF/data/initial/administrator.csv
  src/main/resources/WEB-INF/data/initial/user-account.csv
Labels: enhancement, Group, mandatory

#300 feat(Group): Task-055-BannedPassengerService #130
  src/main/java/acme/constraints/PassportValidator.java
  src/main/java/acme/constraints/bannedPassengers/BannedPassengerValidator.java
  src/main/java/acme/constraints/bannedPassengers/ValidBannedPassenger.java
  src/main/java/acme/entities/bannedPassengers/BannedPassenger.java
  src/main/resources/WEB-INF/data/sample/bannedPassenger.csv
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
Labels: enhancement, Group, suplementary-II

#310 feat(Student4): Task 020 - Testing Assistance Agent
  src/main/resources/WEB-INF/data/sample/assistanceAgent.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: enhancement, Individual, mandatory

#313 feat(student2): follow up changes done!
  src/main/java/acme/entities/passenger/Passenger.java
Labels: bug, enhancement, Individual, mandatory

#314 fixed(student): Task 20 - Testing Assistance Agents
  src/main/java/acme/realms/AssistanceAgent.java
  src/main/resources/WEB-INF/data/sample/assistanceAgent.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: bug, Individual, mandatory

#316 fix(Student4): Task 014/R1 - Claim Entity
  src/main/java/acme/entities/claims/Claim.java
  src/main/java/acme/entities/trackingLog/Resolution.java
Labels: bug, enhancement, Individual, mandatory

#320 fix(Student4):Task016/R1-UMLDomain
  reports/Student #4/D02/D02 - Student4 - UML.pdf
  reports/Student #4/D02/D02 - Student4 - UML.uxf
Labels: bug, enhancement, Individual, suplementary-I

#323 fix(Student4):Task20/R2 - Testing Assistance Agent not working properly
  src/main/java/acme/entities/claims/Claim.java
  src/main/java/acme/entities/trackingLogs/TrackingLog.java
  src/main/java/acme/realms/AssistanceAgent.java
  src/main/resources/WEB-INF/data/sample/claim.csv
  src/main/resources/WEB-INF/data/sample/trackingLog.csv
Labels: bug, enhancement, Individual, mandatory

#324 fix(group): Task 063/R2 - Airline entity fixed #302
  src/main/java/acme/entities/airlines/Airline.java
  src/main/java/acme/entities/airports/Airport.java
Labels: bug, Group, mandatory

#327 fix(student1): Task 021/R1 - Manager entity #304
  src/main/java/acme/constraints/flights/FlightNumberValidator.java
  src/main/java/acme/entities/airlines/Airline.java
  src/main/java/acme/entities/flights/Leg.java
  src/main/java/acme/realms/Manager.java
  src/main/resources/WEB-INF/data/sample/leg.csv
  src/main/resources/WEB-INF/data/sample/manager.csv
Labels: bug, enhancement, Individual, mandatory

#328 feat(student4): Task 017 - Assistance Agent dashboard
  src/main/java/acme/forms/AssistanceAgentDashboards.java
Labels: enhancement, Individual, suplementary-I

#332 Task 023/R2 - Leg entity #306
  src/main/java/acme/entities/flights/Leg.java
Labels: bug, enhancement, Individual, mandatory

#334 fix(student2): fixing column unique done
  src/main/java/acme/entities/bookings/Booking.java
Labels: bug

#331 fix(Group): enhance validation for airport attributes
  src/main/java/acme/entities/airports/Airport.java
Labels: bug, enhancement, Group, mandatory

#337 fix(group): Task 059/R3 - Aircraft entity #336
  src/main/java/acme/entities/aircrafts/Aircraft.java
Labels: bug, enhancement, Group, mandatory

#338 Task 009 r1 flight assigment entity
  src/main/java/acme/entities/flightAssignment/FlightAssignment.java
  src/main/java/acme/realms/flightCrewMembers/FlightCrewMember.java
Labels: bug, enhancement, Individual, mandatory

#309 fix(Group): Follow up changes done
  src/main/java/acme/entities/services/Service.java
  src/main/resources/WEB-INF/data/sample/service.csv
Labels: bug, enhancement, Group, mandatory

#342 fixed(Student3) Task 009R1-flightcrewmembersentity
  src/main/java/acme/realms/flightCrewMembers/FlightCrewMember.java
Labels: bug, enhancement, Individual, mandatory

#347 fixed(Student3) Task008-R1- fixed activitylogEntity
  src/main/java/acme/entities/activityLog/ActivityLog.java
Labels: bug, enhancement, Individual, mandatory

#350 fix(group): Task 061/R1 - UMLDomainModel #346
  reports/Group/D02/D02 - Group - UML.pdf
  reports/Group/D02/D02 - Group - UML.uxf
Labels: bug, documentation, Group, suplementary-I

#351 fix(student5): Task 038/R1 - Simplify validation annotations and change healthTestP…
  src/main/java/acme/realms/Technician.java
Labels: enhancement

#352 feat(student5): Task 040 - Technician sample data
  src/main/java/acme/constraints/LicenseValidator.java
  src/main/resources/WEB-INF/data/sample/technician.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: testing, Individual, mandatory

#354 feat(Group): Task 057 - Analysis Report Done
  reports/Group/D02/D02 - Group - Analysis report.docx
Labels: documentation, Group, suplementary-I

#355 feat(Student4): Task 013 - Analysis Report Done ft Requirements
  reports/Student #4/D02/D02 - 04 - Requirements - Student#4.docx
  reports/Student #4/D02/D02 - Student#4 - Analysis report.docx
Labels: documentation, Individual, suplementary-II

#356 feat(Student4): Task 012 - Planning and Progress Report Done
  reports/Student #4/D02/D02 - Student#4 - Planning and progress report.docx
Labels: documentation, Individual, suplementary-I

#357 feat(student1): Task 029 - Analysis report #105
  reports/Student #1/D02/D02 - Student#1 - Analysis report.docx
Labels: documentation, Individual, suplementary-II

#353 feat(student2): UML and Analysis Report
  reports/Student #2/02 - Requirements - Student #2.docx
  reports/Student #2/D01/D01 - 02 - Requirements - Student #2.docx
  reports/Student #2/D02/D02 - Student#2 - Analysis report.docx
  reports/Student #2/D02/D02 - Student#2 - Planning and progress report.docx
  reports/Student #2/D02/UML/D02-Student2-UML.pdf
  reports/Student #2/D02/UML/D02-Student2-UML.uxf
Labels: documentation, Individual, mandatory, suplementary-I

#358 feat(student5): Task 041/R1 - Maintenance records entity
  src/main/java/acme/entities/maintenanceRecords/MaintenanceRecord.java
  src/main/resources/WEB-INF/data/sample/maintenanceRecord.csv
Labels: bug, Individual, mandatory

#359 feat(student5): Task 037/R1 - Task entity
  src/main/java/acme/entities/tasks/Task.java
  src/main/resources/WEB-INF/data/sample/maintenanceRecordTask.csv
  src/main/resources/WEB-INF/data/sample/task.csv
Labels: enhancement, Individual, mandatory

#361 feat(student5): Task 036 - Technician dashboard
  src/main/java/acme/forms/TechnicianDashboard.java
Labels: enhancement, Individual, suplementary-I

#362 feat(student1): Task 030 - Planning and progress report #106
  reports/Student #1/D02/D02 - Student#1 - Planning and progress report.docx
Labels: documentation, Individual, suplementary-II

#363 feat(student5): Task 035 - UML domain model
  reports/Student #5/D01 - 05 - Requirements - Student #5.docx
  reports/Student #5/D01/D01 - 05 - Requirements - Student #5.docx
  reports/Student #5/D02/D02 - Student5 - UML.pdf
  reports/Student #5/D02/D02 - Student5 - UML.uxf
Labels: documentation, Individual, suplementary-I

#360 feat(group): Task 031/R1 - Review Entity
  src/main/java/acme/entities/reviews/Review.java
  src/main/resources/WEB-INF/data/sample/review.csv
Labels: enhancement, Group, mandatory

#366 fixed(Group): Task054-fixedDashBoard
  src/main/java/acme/forms/AdministratorDashboard.java
Labels: bug, enhancement, Group, suplementary-I

#368 feat(student5): Task 033 - Analysis report
  reports/Student #5/D02/D02 - Student#5 - Analysis report.docx
Labels: documentation, Individual, suplementary-II

#369 fixed(Group): Task 061-R2-UMLWellDone
  reports/Group/D02/D02 - Group - UML.pdf
  reports/Group/D02/D02 - Group - UML.uxf
Labels: bug, documentation, Group, suplementary-I

#370 feat(Student3): Task-004-UMLDone
  reports/Student #3/D02/D02 - Student3- UML.pdf
  reports/Student #3/D02/D02 - Student3- UML.uxf
Labels: documentation, Group, suplementary-I

#372 fixed(Student3): Task007-R2-SampleDataFlightCrewMembers
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: bug, enhancement, Individual, suplementary-I

#374 fixed(Group): Task054-R2-AdministratorDashboard
  src/main/java/acme/forms/AdministratorDashboard.java
Labels: bug, enhancement, Group, suplementary-I

#376 feat(student5): Task 032 - Planning and progress report
  reports/Student #5/05 - Requirements - Student #5.docx
  reports/Student #5/D01 - 05 - Requirements - Student #5.docx
  reports/Student #5/D02/D02 - Student#5 - Planning and progress report.docx
Labels: documentation, Individual, suplementary-II

#377 fixed(Group): Task-061-R3-fixedUMLDomainModel.
  reports/Group/D02/D02 - Group - UML.pdf
  reports/Group/D02/D02 - Group - UML.uxf
Labels: bug, documentation, Group, suplementary-I

#380 fixed(Student3): Task007-R3-SampleDataFlightCrewMember
  src/main/resources/WEB-INF/data/sample/flightCrewMember.csv
Labels: bug, enhancement, Individual, suplementary-I

#379 feat(student1): Task 028 - Weather conditions service #104
  .gitignore
  README.txt
  reports/Student #1/01 - Requirements - Student #1.docx
  src/main/java/acme/features/weather/WeatherCondition.java
  src/main/java/acme/features/weather/WeatherController.java
  src/main/java/acme/features/weather/WeatherResponse.java
  src/main/java/acme/features/weather/WeatherService.java
  src/main/resources/application.properties
Labels: enhancement, Individual, suplementary-II

#382 fix(student1): Documents fixed
  reports/Student #1/D02/D02 - Student#1 - Analysis report.docx
  reports/Student #1/D02/D02 - Student#1 - Planning and progress report.docx
  reports/Student #1/D02/D02 - Student1 - UML.pdf
  reports/Student #1/D02/D02 - Student1 - UML.uxf
Labels: bug, documentation, Individual, suplementary-II

#384 feat(Group): Planning and progress done #133
  reports/Group/00 - Requirements - Group.docx
  reports/Group/D01/D01 - 00 - Requirements - Group.docx
  reports/Group/D02/D02 - Group - Planning and progress report.docx
Labels: documentation, Group, suplementary-II

#386 Task 064 new project version
  .classpath
  .gitignore
  .settings/org.eclipse.wst.common.component
Labels: enhancement, Group

#388 Task 064/R1 - New project version #387
  .classpath
  .gitignore
  .settings/org.eclipse.wst.common.component
Labels: bug, enhancement, Group

#501 feat(Student2): Recommendation destination board done!
  .project
  .settings/org.eclipse.wst.common.component
  src/main/java/acme/features/recommendation/Recommendation.java
Labels: enhancement, Individual, suplementary-II

#502 feat(student2): task 068: Operations by any principals on service #395
  src/main/java/acme/features/any/service/AnyServiceController.java
  src/main/java/acme/features/any/service/AnyServiceRepository.java
  src/main/resources/WEB-INF/views/fragments/footer.jsp
Labels: enhancement, Group, mandatory

#503 feat(Student4): Flight Status done! Solved errors on csv files
  src/main/java/acme/features/flightStatus/FlightStatus.java
  src/main/resources/WEB-INF/data/sample/assistanceAgent.csv
  src/main/resources/WEB-INF/data/sample/claim.csv
  src/main/resources/WEB-INF/data/sample/trackingLog.csv
Labels: bug, testing, Individual

#507 fix(student5): update entities from Follow-up feedback
  src/main/java/acme/entities/maintenanceRecords/MaintenanceRecord.java
  src/main/java/acme/entities/maintenanceRecords/MaintenanceRecordTask.java
  src/main/java/acme/entities/tasks/Task.java
Labels: bug, Individual, mandatory

#534 fix(group):fix Review entity relationship constraints
  src/main/java/acme/entities/reviews/Review.java
Labels: bug, Group, mandatory

#537 fix(student1): fixing Task 082 - Follow Up. #536
  src/main/java/acme/features/manager/flight/ManagerFlightCreateService.java
  src/main/java/acme/features/manager/flight/ManagerFlightListService.java
  src/main/java/acme/features/manager/flight/ManagerFlightRepository.java
  src/main/java/acme/features/manager/flight/ManagerFlightShowService.java
  src/main/resources/WEB-INF/views/manager/flight/list.jsp
  src/main/resources/WEB-INF/views/manager/flight/messages-en.i18n
  src/main/resources/WEB-INF/views/manager/flight/messages-es.i18n
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
Labels: bug, enhancement, Individual, mandatory

#539 Task 094 operations by customers on bookings
  .settings/org.eclipse.wst.common.component
  src/main/java/acme/features/any/service/AnyServiceRepository.java
  src/main/java/acme/features/customer/booking/CustomerBookingController.java
  src/main/java/acme/features/customer/booking/CustomerBookingCreateService.java
  src/main/java/acme/features/customer/booking/CustomerBookingListService.java
  src/main/java/acme/features/customer/booking/CustomerBookingRepository.java
  src/main/java/acme/features/customer/booking/CustomerBookingShowService.java
  src/main/java/acme/features/customer/booking/CustomerBookingUpdateService.java
  src/main/resources/WEB-INF/data/sample/service.csv
  src/main/resources/WEB-INF/views/customer/booking/form.jsp
  src/main/resources/WEB-INF/views/customer/booking/list.jsp
  src/main/resources/WEB-INF/views/customer/booking/messages-en.i18n
  src/main/resources/WEB-INF/views/customer/booking/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, Individual, mandatory

#541 hotfix:Sampledata
  src/main/resources/WEB-INF/data/sample/activityLog.csv
  src/main/resources/WEB-INF/data/sample/flightAssignment.csv
  src/main/resources/WEB-INF/data/sample/flightCrewMember.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
  src/main/resources/application.properties
Labels: bug, enhancement, Individual, mandatory

#569 Task 094 R1 operations by customers on bookings
  src/main/java/acme/constraints/ValidLocatorCode.java
  src/main/java/acme/constraints/bookings/BookingValidator.java
  src/main/java/acme/constraints/bookings/ValidBooking.java
  src/main/java/acme/constraints/customer/CustomerValidator.java
  src/main/java/acme/entities/bookings/Booking.java
  src/main/java/acme/entities/bookings/BookingRepository.java
  src/main/java/acme/features/customer/booking/CustomerBookingController.java
  src/main/java/acme/features/customer/booking/CustomerBookingCreateService.java
  src/main/java/acme/features/customer/booking/CustomerBookingListService.java
  src/main/java/acme/features/customer/booking/CustomerBookingRepository.java
  src/main/java/acme/features/customer/booking/CustomerBookingShowService.java
  src/main/java/acme/features/customer/booking/CustomerBookingUpdateService.java
  src/main/java/acme/realms/customer/Customer.java
  src/main/java/acme/realms/customer/CustomerRepository.java
  src/main/resources/WEB-INF/data/sample/booking.csv
  src/main/resources/WEB-INF/data/sample/customer.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
  src/main/resources/WEB-INF/views/customer/booking/form.jsp
  src/main/resources/WEB-INF/views/customer/booking/messages-en.i18n
  src/main/resources/WEB-INF/views/customer/booking/messages-es.i18n
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
Labels: enhancement, Individual, mandatory

#570 "feat(Student3) - Task 131- Falta create, update, publish"
  src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentController.java
  src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentCreateService.java
  src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentListService.java
  src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentRepository.java
  src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentShowService.java
  src/main/resources/WEB-INF/views/flight-crew-member/flight-assignment/form.jsp
  src/main/resources/WEB-INF/views/flight-crew-member/flight-assignment/list.jsp
  src/main/resources/WEB-INF/views/flight-crew-member/flight-assignment/messages-en.i18n
  src/main/resources/WEB-INF/views/flight-crew-member/flight-assignment/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, Individual, mandatory

#538 Task 073 operations by administrators on services
  .settings/org.eclipse.wst.common.component
  src/main/java/acme/constraints/PromoCodeValidator.java
  src/main/java/acme/constraints/ValidPromoCode.java
  src/main/java/acme/entities/services/Service.java
  src/main/java/acme/features/administrator/service/AdministratorServiceController.java
  src/main/java/acme/features/administrator/service/AdministratorServiceCreateService.java
  src/main/java/acme/features/administrator/service/AdministratorServiceDeleteService.java
  src/main/java/acme/features/administrator/service/AdministratorServiceListService.java
  src/main/java/acme/features/administrator/service/AdministratorServiceRepository.java
  src/main/java/acme/features/administrator/service/AdministratorServiceShowService.java
  src/main/java/acme/features/administrator/service/AdministratorServiceUpdateService.java
  src/main/resources/WEB-INF/data/sample/service.csv
  src/main/resources/WEB-INF/views/administrator/service/form.jsp
  src/main/resources/WEB-INF/views/administrator/service/list.jsp
  src/main/resources/WEB-INF/views/administrator/service/messages-en.i18n
  src/main/resources/WEB-INF/views/administrator/service/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/footer.jsp
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
Labels: enhancement, Group, mandatory

#568 fix(Group): fixing routes for advertisement
  src/main/java/acme/components/AdvertisementController.java
  src/main/java/acme/components/AdvertisementRepository.java
Labels: bug, Group, mandatory
