Repository pabmejbui/Acme-ANS, pull requests merged in 2025-07, with the labels that each got.

#793 fix(Student3): Task 223 - Fixing the bugs in task 9 #790
  src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogPublishService.java
Labels: bug, Individual, mandatory

#794 fix(Student3): Task 223 - Fixing the bugs in task 9 #790
  src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogPublishService.java
Labels: bug, Individual, mandatory

#795 fix(Student3): Task 223 - Fixing the bugs in task 9 #790
  src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogPublishService.java
Labels: bug, Individual, mandatory

#805 fix(student1): Task 197 - Mistake in the flight entity #745
  src/main/java/acme/constraints/flights/FlightValidator.java
  src/main/java/acme/constraints/flights/TagValidator.java
  src/main/java/acme/constraints/flights/ValidTag.java
  src/main/java/acme/entities/flights/Flight.java
Labels: bug, Individual, mandatory

#807 Task 200 - Bug in the "my legs" button of the create form #748
  src/main/resources/WEB-INF/views/manager/flight/form.jsp
  src/main/resources/WEB-INF/views/manager/leg/form.jsp
Labels: bug, Individual, mandatory

#816 fix(Student3): Task 223 - Fixing the bugs in task 9 #790
  src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogCreateService.java
  src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogPublishService.java
  src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogRepository.java
  src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogShowService.java
  src/main/java/acme/features/flightCrewMember/activityLog/FlightCrewMemberActivityLogUpdateService.java
  src/main/resources/WEB-INF/data/sample/flightAssignment.csv
Labels: bug, Individual, mandatory

#827 Task 220 r1 produce test suite for passengers
  src/main/java/acme/features/customer/passenger/CustomerPassengerPublishService.java
  src/test/resources/customer/passenger/CreatePassenger.hack
  src/test/resources/customer/passenger/CreatePassenger.safe
  src/test/resources/customer/passenger/DeletePassenger.safe
  src/test/resources/customer/passenger/ListPassenger.hack
  src/test/resources/customer/passenger/ListPassenger.safe
  src/test/resources/customer/passenger/PublishPassenger.hack
  src/test/resources/customer/passenger/PublishPassenger.safe
  src/test/resources/customer/passenger/ShowPassenger.hack
  src/test/resources/customer/passenger/ShowPassenger.safe
  src/test/resources/customer/passenger/UpdatePassenger.hack
  src/test/resources/customer/passenger/UpdatePassenger.safe
Labels: bug, testing, Individual, mandatory

#829 fix: indexes updated
  src/main/java/acme/entities/bookings/Booking.java
  src/main/java/acme/entities/bookings/BookingRecord.java
  src/main/java/acme/entities/passenger/Passenger.java
  src/main/java/acme/realms/customer/Customer.java
Labels: bug, Individual, mandatory

#830 feat: testing report updated
  reports/Student #2/D05/Testing report  - Student #2.docx
Labels: documentation, enhancement, Individual, mandatory

#838 fix(Student3): Task 223 - Fixing the bugs in task 9 #790
  src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentCreateService.java
  src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentPublishService.java
  src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentShowService.java
  src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentUpdateService.java
  src/main/resources/WEB-INF/views/flight-crew-member/flight-assignment/form.jsp
Labels: bug, Individual, mandatory

#839 feat: five mutations test done!
  reports/Student #2/D05/Testing report  - Student #2.docx
  reports/Student #2/D05/~$sting report  - Student #2.docx
  reports/Student #2/D05/~WRL0005.tmp
  src/main/java/acme/features/customer/booking/CustomerBookingCreateService.java
Labels: documentation, Individual, suplementary-I

#840 hotfix: mutations in testing report saved
  reports/Student #2/D05/Testing report  - Student #2.docx
  reports/Student #2/D05/~$sting report  - Student #2.docx
  reports/Student #2/D05/~WRL0005.tmp
Labels: bug, Individual, suplementary-I

#845 feat: lint report done
  reports/Student #2/C2/Lint report  - Student #2.docx
  reports/Student #2/C2/Testing report  - Student #2.docx
Labels: documentation, Individual, suplementary-I

#851 feat(student1): Task 240 - Produce a test suite for R8 and R9 #834
  reports/Student #1/D02/Student1 - UML.uxf
  src/main/java/acme/constraints/flights/FlightNumberValidator.java
  src/main/java/acme/constraints/flights/FlightValidator.java
  src/main/java/acme/constraints/flights/TagValidator.java
  src/main/java/acme/constraints/flights/ValidFlight.java
  src/main/java/acme/entities/flights/Flight.java
  src/main/java/acme/features/manager/flight/ManagerFlightCreateService.java
  src/main/java/acme/features/manager/flight/ManagerFlightDeleteService.java
  src/main/java/acme/features/manager/flight/ManagerFlightPublishService.java
  src/main/java/acme/features/manager/flight/ManagerFlightRepository.java
  src/main/java/acme/features/manager/flight/ManagerFlightUpdateService.java
  src/main/java/acme/features/manager/leg/ManagerLegCreateService.java
  src/main/java/acme/features/manager/leg/ManagerLegDeleteService.java
  src/main/java/acme/features/manager/leg/ManagerLegPublishService.java
  src/main/java/acme/features/manager/leg/ManagerLegRepository.java
  src/main/java/acme/features/manager/leg/ManagerLegUpdateService.java
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
  src/test/resources/manager/DUMMY.txt
  src/test/resources/manager/flight/CreateFlight.hack
  src/test/resources/manager/flight/CreateFlight.safe
  src/test/resources/manager/flight/DeleteFlight.hack
  src/test/resources/manager/flight/DeleteFlight.safe
  src/test/resources/manager/flight/ListFlight.hack
  src/test/resources/manager/flight/ListFlight.safe
  src/test/resources/manager/flight/PublishFlight.hack
  src/test/resources/manager/flight/PublishFlight.safe
  src/test/resources/manager/flight/ShowFlight.hack
  src/test/resources/manager/flight/ShowFlight.safe
  src/test/resources/manager/flight/ShowFlight2.hack
  src/test/resources/manager/flight/UpdateFlight.hack
  src/test/resources/manager/flight/UpdateFlight.safe
  src/test/resources/manager/leg/CreateLeg.hack
  src/test/resources/manager/leg/CreateLeg.safe
  src/test/resources/manager/leg/DeleteLeg.hack
  src/test/resources/manager/leg/DeleteLeg.safe
  src/test/resources/manager/leg/ListLeg.hack
  src/test/resources/manager/leg/ListLeg.safe
  src/test/resources/manager/leg/PublishLeg.hack
  src/test/resources/manager/leg/PublishLeg.safe
  src/test/resources/manager/leg/ShowLeg.hack
  src/test/resources/manager/leg/ShowLeg.safe
  src/test/resources/manager/leg/UpdateLeg.hack
  src/test/resources/manager/leg/UpdateLeg.safe
Labels: enhancement, Individual, mandatory

#852 feat: analysys report for D03 done
  reports/Student #2/D03/D03 - Student#2 - Analysis report.docx
  reports/Student #2/D03/~$3 - Student#2 - Analysis report.docx
  reports/Student #2/D03/~WRL0267.tmp
Labels: documentation, Individual, suplementary-II

#877 feat(Group): Task 243 - Produce a plagiarism authorization document #842
  reports/Group/Autorización_de_uso_de_materiales_académicos_(1)[1].docx
Labels: documentation, Group

#883 Task 235 operations by technicians on maintenance records
  src/main/java/acme/entities/maintenanceRecords/MaintenanceRecord.java
  src/main/java/acme/entities/tasks/Task.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordController.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordCreateService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordDeleteService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordListService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordPublishService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordRepository.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordShowService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordUpdateService.java
  src/main/java/acme/realms/technician/Technician.java
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/technician/maintenance-record/form.jsp
  src/main/resources/WEB-INF/views/technician/maintenance-record/list.jsp
  src/main/resources/WEB-INF/views/technician/maintenance-record/messages-en.i18n
  src/main/resources/WEB-INF/views/technician/maintenance-record/messages-es.i18n
Labels: enhancement, Individual, mandatory

#884 feat(student1): Task 239 - Create appropiate indices #832
  src/main/java/acme/entities/flights/Flight.java
  src/main/java/acme/entities/flights/Leg.java
Labels: enhancement, Individual, mandatory

#888 Task 236 operations by technicians on tasks
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordDeleteService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordListService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordPublishService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordShowService.java
  src/main/java/acme/features/technician/maintenanceRecordTask/TechnicianMaintenanceRecordTaskController.java
  src/main/java/acme/features/technician/maintenanceRecordTask/TechnicianMaintenanceRecordTaskCreateService.java
  src/main/java/acme/features/technician/maintenanceRecordTask/TechnicianMaintenanceRecordTaskDeleteService.java
  src/main/java/acme/features/technician/maintenanceRecordTask/TechnicianMaintenanceRecordTaskRepository.java
  src/main/java/acme/features/technician/task/TechnicianTaskController.java
  src/main/java/acme/features/technician/task/TechnicianTaskCreateService.java
  src/main/java/acme/features/technician/task/TechnicianTaskDeleteService.java
  src/main/java/acme/features/technician/task/TechnicianTaskListService.java
  src/main/java/acme/features/technician/task/TechnicianTaskPublishService.java
  src/main/java/acme/features/technician/task/TechnicianTaskRepository.java
  src/main/java/acme/features/technician/task/TechnicianTaskShowService.java
  src/main/java/acme/features/technician/task/TechnicianTaskUpdateService.java
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/technician/maintenance-record-task/form.jsp
  src/main/resources/WEB-INF/views/technician/maintenance-record-task/list.jsp
  src/main/resources/WEB-INF/views/technician/maintenance-record-task/messages-en.i18n
  src/main/resources/WEB-INF/views/technician/maintenance-record-task/messages-es.i18n
  src/main/resources/WEB-INF/views/technician/maintenance-record/form.jsp
  src/main/resources/WEB-INF/views/technician/maintenance-record/list.jsp
  src/main/resources/WEB-INF/views/technician/maintenance-record/messages-en.i18n
  src/main/resources/WEB-INF/views/technician/maintenance-record/messages-es.i18n
  src/main/resources/WEB-INF/views/technician/task/form.jsp
  src/main/resources/WEB-INF/views/technician/task/list.jsp
  src/main/resources/WEB-INF/views/technician/task/messages-en.i18n
  src/main/resources/WEB-INF/views/technician/task/messages-es.i18n
Labels: enhancement, Individual, mandatory

#902 feat(student1): Task 241 - Produce a testing report #836
  reports/Student #1/01 - Requirements - Student #1.docx
  reports/Student #1/C2/01 - Requirements - Student #1.docx
  reports/Student #1/C2/link-to-C2-dashboard
  reports/Student #1/D01/link-to-D01-dashboard
  reports/Student #1/D02/link-to-D02-dashboard
  reports/Student #1/D03/link-to-D03-dashboard
  reports/Student #1/D04/Testing report - Student #1.docx
  reports/Student #1/D04/link-to-D04-dashboard
Labels: documentation, enhancement, Individual, mandatory

#903 feat(Student3): Task 223/R1 - Fixing the bugs in task 9 #899
  src/test/resources/flightCrewMember/flightAssignment/publish.safe
Labels: bug, Individual, mandatory

#904 feat: Planning and progress D04 done
  reports/C2/Autorización_de_uso_de_materiales_académicos.docx
  reports/Student #2/D04/D04  - Analysis report - Student#2.docx
  reports/Student #2/D04/D04  - Planning and progress report - Student#2.docx
  reports/Student #2/D04/~$4  - Planning and progress report - Student#2.docx
  reports/Student #2/D04/~WRL0101.tmp
Labels: documentation, Individual, suplementary-II

#913 Task 223/R2 - Fixing the bugs in task 9 #911
  src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentPublishService.java
  src/main/java/acme/features/flightCrewMember/flightAssignment/FlightCrewMemberFlightAssignmentUpdateService.java
  src/test/resources/flightCrewMember/flightAssignment/publish.safe
  src/test/resources/flightCrewMember/flightAssignment/update.safe
Labels: bug, Individual, mandatory

#916 Task 270 create appropriate indices for your entities if required
  src/main/java/acme/entities/activityLog/ActivityLog.java
  src/main/java/acme/entities/flightAssignment/FlightAssignment.java
Labels: bug, Individual, mandatory

#917 fix(Student3): Task-270-Fixing indices
  src/main/java/acme/entities/activityLog/ActivityLog.java
  src/main/java/acme/entities/flightAssignment/FlightAssignment.java
Labels: bug, Individual, mandatory

#926 feat(Student3): Task 272- Produce a testing report. #924
  reports/Student #3/C2/C2 - Testing report  - Student #3.docx
Labels: documentation, Individual, mandatory

#927 fix(group): Task 273 - Logo icon, banner and more update #925
  CHANGELOG.txt
  README.txt
  src/main/resources/META-INF/resources/images/banner.png
Labels: Group, mandatory
