Repository pabmejbui/Acme-ANS, pull requests merged in 2025-02, with the labels that each got.

#14 feat(student1): Task 1 - Modify the anonymus menu #10
  .classpath
  .project
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: enhancement

#16 feat(student2): Task 1 - Modify the anonymus menu #15
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: enhancement

#17 Student1 - Task 2 - Link to planning dashboard #11
  .settings/org.eclipse.wst.common.component
  CHANGELOG.txt
  reports/Group/DUMMY.txt
  reports/Student #1/D01/D01 - 01 - Requirements - Student #1.docx
  reports/Student #2/DUMMY.txt
  reports/Student #3/DUMMY.txt
  reports/Student #4/DUMMY.txt
  reports/Student #5/DUMMY.txt
Labels: documentation

#24 Student1 - Task 25 - Planning and progress report #13
  reports/Student #1/D01/D01 - Student#1 - Planning and progress report.docx
Labels: documentation

#23 Student1 - Task24 - Analysis report #12
  reports/Student #1/D01/D01 - Student#1 - Analysis report.docx
Labels: documentation

#22 fix(group): fixing some fragments
  src/main/resources/WEB-INF/views/fragments/banner-en.i18n
  src/main/resources/WEB-INF/views/fragments/banner-es.i18n
  src/main/resources/WEB-INF/views/fragments/company-en.i18n
  src/main/resources/WEB-INF/views/fragments/company-es.i18n
  src/main/resources/WEB-INF/views/fragments/title-en.i18n
  src/main/resources/WEB-INF/views/fragments/title-es.i18n
  src/main/resources/WEB-INF/views/fragments/welcome-en.i18n
  src/main/resources/WEB-INF/views/fragments/welcome-es.i18n
  src/main/resources/banner.txt
Labels: bug

#28 Student2 - Task24 - Analysis report #25
  reports/Student #2/D01/D01 - 02 - Requirements - Student #2.docx
  reports/Student #2/D01/D01 - Student#2 - Analysis report.docx
  reports/Student #2/DUMMY.txt
Labels: documentation

#30 feat(workflow): trying a workflow for issue automization
  .github/workflows/move_issue.yml
Labels: enhancement

#27 Group - Task 23 - Configuration report #7
  reports/Group/D01 - Group - Configuration Report.docx
  reports/Group/DUMMY.txt
  reports/Student #1/D01/D01 - Student#1 - Planning and progress report.docx
Labels: documentation

#31 feat(student5): Task 1 - Modify the anonymous menu #18
  .classpath
  .settings/org.eclipse.wst.common.component
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: enhancement

#34 feat(student4): Task 1 - Modify the anonymous menu #33
  .project
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: enhancement

#38 fix(project): problem with .project file
  .project
Labels: bug

#39 Student3 - Task 1 - Modify the Annonimous Menu #37
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: enhancement

#41 Develop
  .settings/org.eclipse.wst.common.component
  CHANGELOG.txt
  reports/Group/D01 - Group - Configuration Report.docx
  reports/Student #1/D01/D01 - 01 - Requirements - Student #1.docx
  reports/Student #1/D01/D01 - Student#1 - Analysis report.docx
  reports/Student #1/D01/D01 - Student#1 - Planning and progress report.docx
  reports/Student #2/D01/D01 - 02 - Requirements - Student #2.docx
  reports/Student #2/D01/D01 - Student#2 - Analysis report.docx
  reports/Student #2/D01/D01 - Student#2 - Planning and progress report.docx
  reports/Student #3/DUMMY.txt
  reports/Student #4/DUMMY.txt
  reports/Student #5/DUMMY.txt
  src/main/resources/WEB-INF/views/fragments/banner-en.i18n
  src/main/resources/WEB-INF/views/fragments/banner-es.i18n
  src/main/resources/WEB-INF/views/fragments/company-en.i18n
  src/main/resources/WEB-INF/views/fragments/company-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/fragments/title-en.i18n
  src/main/resources/WEB-INF/views/fragments/title-es.i18n
  src/main/resources/WEB-INF/views/fragments/welcome-en.i18n
  src/main/resources/WEB-INF/views/fragments/welcome-es.i18n
  src/main/resources/banner.txt
Labels: bug

#57 doc(student4): Task 24 - Produce Analysis Report #32
  reports/Student #4/D01/D01 - Student#4 - Analysis report.docx
Labels: documentation

#64 docs(group): Task 36 - Analysis report #8
  reports/Group/D01/D01 - Group - Analysis report.docx
Labels: documentation

#65 hotfix(student2): reports updated
  reports/Student #2/D01/D01 - 02 - Requirements - Student #2.docx
  reports/Student #2/D01/D01 - Student#2 - Analysis report.docx
  reports/Student #2/D01/D01 - Student#2 - Planning and progress report.docx
Labels: documentation

#66 feat(Student3): Task2-LinkPlanningDashBoard
  reports/Student #3/D01/D01 - 03 - Requirements - Student #3.docx
Labels: documentation

#69 hotfix(student2): all docs should be ok now
  reports/Student #2/D01/D01 - Student#2 - Analysis report.docx
Labels: documentation, invalid

#72 feat(group): Task 21 - WIS report #5
  reports/Group/D01/D01- Group- WIS Architecture Report.docx
Labels: documentation

#73 fixed(student3): requirements fixed. #42
  reports/Student #3/D01/D01 - 03 - Requirements - Student #3.docx
Labels: bug, documentation

#74 hotfix(student2): fixing id number in requirements
  reports/Student #2/D01/D01 - 02 - Requirements - Student #2.docx
  reports/Student #2/D01/D01 - Student#2 - Planning and progress report.docx
Labels: documentation

#91 docs(group): Task 22 - Testing WIS Report #6
  reports/Group/D01/D01 - Group - Testing WIS Report.docx
Labels: documentation

#85 docs(student5): Task 24 - Analysis report #20
  reports/Student #5/D01/D01 - 05 - Requirements - Student #5.docx
  reports/Student #5/D01/D01 - Student#5 - Analysis report.docx
  reports/Student #5/DUMMY.txt
Labels: documentation

#96 docs(group): Task 37 - Planning and progress report #9
  reports/Group/D01/D01 - 00 - Requirements - Group.docx
  reports/Group/D01/D01 - Group - Planning and progress report.docx
Labels: documentation

#114 docs(student5): Task 25 - Produce Planning & Progress Report #21
  reports/Student #5/D01/D01 - Student#5 - Planning and progress report.docx
Labels: documentation

#118 fix(group): requirement document fixed
  reports/DUMMY.txt
  reports/Group/D01/D01 - 00 - Requirements - Group.docx
Labels: documentation

#119 fix(group): Task 36 and 37 fixed
  reports/Group/D01/D01 - Group - Analysis report.docx
  reports/Group/D01/D01 - Group - Planning and progress report.docx
Labels: bug, documentation

#228 Group - Task5 - Airline entity
  .classpath
  .gitignore
  .settings/org.eclipse.wst.common.component
  src/main/java/acme/entities/Airline.java
  src/main/java/acme/entities/AirlineType.java
  src/main/java/acme/entities/DUMMY.txt
Labels: enhancement

#225 feat(group): Task 058 - Airport entity #120
  .classpath
  src/main/java/acme/entities/airports/Airport.java
  src/main/java/acme/entities/airports/OperationalScope.java
Labels: enhancement, Group
