Repository pabmejbui/Acme-ANS, pull requests merged in 2025-05, with the labels that each got.

#661 fix: some validating changes
  .classpath
  .project
  .settings/org.eclipse.wst.common.component
  src/main/java/acme/constraints/PassportValidator.java
  src/main/java/acme/constraints/ValidPassport.java
  src/main/java/acme/entities/bookings/Booking.java
  src/main/java/acme/entities/passenger/Passenger.java
  src/main/java/acme/features/customer/booking/CustomerBookingCreateService.java
  src/main/java/acme/features/customer/booking/CustomerBookingDeleteService.java
  src/main/java/acme/features/customer/booking/CustomerBookingPublishService.java
  src/main/java/acme/features/customer/booking/CustomerBookingRepository.java
  src/main/java/acme/features/customer/booking/CustomerBookingShowService.java
  src/main/java/acme/features/customer/booking/CustomerBookingUpdateService.java
  src/main/resources/WEB-INF/data/sample/booking.csv
  src/main/resources/WEB-INF/data/sample/bookingRecord.csv
  src/main/resources/WEB-INF/data/sample/passenger.csv
  src/main/resources/WEB-INF/views/customer/booking/form.jsp
  src/main/resources/WEB-INF/views/customer/booking/messages-en.i18n
  src/main/resources/WEB-INF/views/customer/booking/messages-es.i18n
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
Labels: bug, enhancement

#662 Task 100 operations by customer on dashboards
  CHANGELOG.txt
  src/main/java/acme/features/customer/customerDashboard/CustomerDashboardController.java
  src/main/java/acme/features/customer/customerDashboard/CustomerDashboardRepository.java
  src/main/java/acme/features/customer/customerDashboard/CustomerDashboardShowService.java
  src/main/java/acme/forms/CustomerDashboard.java
  src/main/resources/WEB-INF/views/customer/customer-dashboard/form.jsp
  src/main/resources/WEB-INF/views/customer/customer-dashboard/messages-en.i18n
  src/main/resources/WEB-INF/views/customer/customer-dashboard/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: enhancement, Individual, suplementary-I

#663 Task 143 create appropriate indices for entities
  src/main/java/acme/entities/bookings/Booking.java
  src/main/java/acme/entities/bookings/BookingRecord.java
  src/main/java/acme/entities/passenger/Passenger.java
  src/main/java/acme/realms/customer/Customer.java
Labels: enhancement, Individual, mandatory

#682 Task 144 produce a test suite for requirements8 and9
  .settings/org.eclipse.wst.common.component
  src/main/java/acme/constraints/NibbleValidator.java
  src/main/java/acme/constraints/ValidLocatorCode.java
  src/main/java/acme/constraints/ValidPassport.java
  src/main/java/acme/constraints/bookings/BookingValidator.java
  src/main/java/acme/constraints/customer/CustomerValidator.java
  src/main/java/acme/constraints/customer/ValidCustomer.java
  src/main/java/acme/constraints/passenger/PassengerValidator.java
  src/main/java/acme/constraints/passenger/ValidPassenger.java
  src/main/java/acme/entities/bookings/Booking.java
  src/main/java/acme/entities/bookings/BookingRecord.java
  src/main/java/acme/entities/passenger/Passenger.java
  src/main/java/acme/features/customer/booking/CustomerBookingCreateService.java
  src/main/java/acme/features/customer/booking/CustomerBookingDeleteService.java
  src/main/java/acme/features/customer/booking/CustomerBookingPublishService.java
  src/main/java/acme/features/customer/booking/CustomerBookingRepository.java
  src/main/java/acme/features/customer/booking/CustomerBookingShowService.java
  src/main/java/acme/features/customer/booking/CustomerBookingUpdateService.java
  src/main/java/acme/features/customer/bookingRecord/BookingRecordRepository.java
  src/main/java/acme/features/customer/bookingRecord/CustomerBookingRecordController.java
  src/main/java/acme/features/customer/bookingRecord/CustomerBookingRecordCreateService.java
  src/main/java/acme/features/customer/bookingRecord/CustomerBookingRecordDeleteService.java
  src/main/java/acme/features/customer/bookingRecord/CustomerBookingRecordRepository.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerCreateService.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerDeleteService.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerListService.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerPublishService.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerRepository.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerShowService.java
  src/main/java/acme/features/customer/passenger/CustomerPassengerUpdateService.java
  src/main/java/acme/realms/customer/Customer.java
  src/main/resources/WEB-INF/data/sample/booking.csv
  src/main/resources/WEB-INF/data/sample/bookingRecord.csv
  src/main/resources/WEB-INF/data/sample/customer.csv
  src/main/resources/WEB-INF/data/sample/passenger.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
  src/main/resources/WEB-INF/views/customer/booking-record/form.jsp
  src/main/resources/WEB-INF/views/customer/booking-record/messages-en.i18n
  src/main/resources/WEB-INF/views/customer/booking-record/messages-es.i18n
  src/main/resources/WEB-INF/views/customer/booking/form.jsp
  src/main/resources/WEB-INF/views/customer/booking/messages-en.i18n
  src/main/resources/WEB-INF/views/customer/booking/messages-es.i18n
  src/main/resources/WEB-INF/views/customer/passenger/form.jsp
  src/main/resources/WEB-INF/views/customer/passenger/list.jsp
  src/main/resources/WEB-INF/views/customer/passenger/messages-en.i18n
  src/main/resources/WEB-INF/views/customer/passenger/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
  src/test/resources/customer/booking/booking.safe
Labels: bug, Individual, mandatory

#684 Task 144 produce a test suite for requirements8 and9
  src/main/java/acme/constraints/PhoneValidator.java
  src/main/java/acme/constraints/ValidPhone.java
  src/main/java/acme/constraints/customer/CustomerValidator.java
  src/main/java/acme/features/authenticated/customer/AuthenticatedCustomerCreateService.java
  src/main/java/acme/features/customer/customerDashboard/CustomerDashboardShowService.java
  src/main/java/acme/realms/customer/Customer.java
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
Labels: bug, Individual, mandatory

#686 Task 119 operations by technicians on maintenance records
  src/main/java/acme/entities/maintenanceRecords/MaintenanceRecord.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordController.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordCreateService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordDeleteService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordListService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordPublishService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordRepository.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordShowService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordUpdateService.java
  src/main/resources/WEB-INF/data/sample/maintenanceRecord.csv
  src/main/resources/WEB-INF/data/sample/technician.csv
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
  src/main/resources/WEB-INF/views/technician/maintenance-record/form.jsp
  src/main/resources/WEB-INF/views/technician/maintenance-record/list.jsp
  src/main/resources/WEB-INF/views/technician/maintenance-record/messages-en.i18n
  src/main/resources/WEB-INF/views/technician/maintenance-record/messages-es.i18n
Labels: enhancement, Individual, mandatory

#688 feat(student5): add task features
  src/main/java/acme/entities/tasks/Task.java
  src/main/java/acme/entities/tasks/TaskType.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordListService.java
  src/main/java/acme/features/technician/maintenanceRecordTask/TechnicianMaintenanceRecordTasksController.java
  src/main/java/acme/features/technician/maintenanceRecordTask/TechnicianMaintenanceRecordTasksCreateService.java
  src/main/java/acme/features/technician/maintenanceRecordTask/TechnicianMaintenanceRecordTasksDeleteService.java
  src/main/java/acme/features/technician/maintenanceRecordTask/TechnicianMaintenanceRecordTasksRepository.java
  src/main/java/acme/features/technician/task/TechnicianMaintenanceRecordTasksListService.java
  src/main/java/acme/features/technician/task/TechnicianTaskController.java
  src/main/java/acme/features/technician/task/TechnicianTaskCreateService.java
  src/main/java/acme/features/technician/task/TechnicianTaskDeleteService.java
  src/main/java/acme/features/technician/task/TechnicianTaskListService.java
  src/main/java/acme/features/technician/task/TechnicianTaskPublishService.java
  src/main/java/acme/features/technician/task/TechnicianTaskRepository.java
  src/main/java/acme/features/technician/task/TechnicianTaskShowService.java
  src/main/java/acme/features/technician/task/TechnicianTaskUpdateService.java
  src/main/resources/WEB-INF/data/sample/maintenanceRecord.csv
  src/main/resources/WEB-INF/data/sample/maintenanceRecordTask.csv
  src/main/resources/WEB-INF/data/sample/task.csv
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/messages-en.i18n
  src/main/resources/WEB-INF/views/messages-es.i18n
  src/main/resources/WEB-INF/views/technician/maintenance-record-task/form.jsp
  src/main/resources/WEB-INF/views/technician/maintenance-record-task/messages-en.i18n
  src/main/resources/WEB-INF/views/technician/maintenance-record-task/messages-es.i18n
  src/main/resources/WEB-INF/views/technician/maintenance-record/form.jsp
  src/main/resources/WEB-INF/views/technician/maintenance-record/list.jsp
  src/main/resources/WEB-INF/views/technician/maintenance-record/messages-en.i18n
  src/main/resources/WEB-INF/views/technician/maintenance-record/messages-es.i18n
  src/main/resources/WEB-INF/views/technician/task/form.jsp
  src/main/resources/WEB-INF/views/technician/task/list.jsp
  src/main/resources/WEB-INF/views/technician/task/messages-en.i18n
  src/main/resources/WEB-INF/views/technician/task/messages-es.i18n
Labels: enhancement, Individual, mandatory

#709 fix(Student3): tuned up d03
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
Labels: bug, enhancement, Individual, mandatory

#710 feeat(student5): add indices
  src/main/java/acme/entities/maintenanceRecords/MaintenanceRecord.java
  src/main/java/acme/entities/maintenanceRecords/MaintenanceRecordTask.java
  src/main/java/acme/entities/tasks/Task.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordController.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordCreateService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordDeleteService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordListService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordPublishService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordRepository.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordShowService.java
  src/main/java/acme/features/technician/maintenanceRecord/TechnicianMaintenanceRecordUpdateService.java
  src/main/java/acme/features/technician/maintenanceRecordTask/TechnicianMaintenanceRecordTasksController.java
  src/main/java/acme/features/technician/maintenanceRecordTask/TechnicianMaintenanceRecordTasksCreateService.java
  src/main/java/acme/features/technician/maintenanceRecordTask/TechnicianMaintenanceRecordTasksDeleteService.java
  src/main/java/acme/features/technician/maintenanceRecordTask/TechnicianMaintenanceRecordTasksRepository.java
  src/main/java/acme/features/technician/task/TechnicianMaintenanceRecordTasksListService.java
  src/main/java/acme/features/technician/task/TechnicianTaskController.java
  src/main/java/acme/features/technician/task/TechnicianTaskCreateService.java
  src/main/java/acme/features/technician/task/TechnicianTaskDeleteService.java
  src/main/java/acme/features/technician/task/TechnicianTaskListService.java
  src/main/java/acme/features/technician/task/TechnicianTaskPublishService.java
  src/main/java/acme/features/technician/task/TechnicianTaskRepository.java
  src/main/java/acme/features/technician/task/TechnicianTaskShowService.java
  src/main/java/acme/features/technician/task/TechnicianTaskUpdateService.java
  src/main/java/acme/realms/technician/Technician.java
Labels: enhancement, Individual, mandatory

#712 feat: indexes done
  src/main/java/acme/entities/bookings/Booking.java
  src/main/java/acme/entities/bookings/BookingRecord.java
  src/main/java/acme/entities/passenger/Passenger.java
  src/main/java/acme/realms/customer/Customer.java
Labels: enhancement, Individual, mandatory

#716 feat: new functional indexes
  src/main/java/acme/entities/bookings/Booking.java
  src/main/java/acme/realms/customer/Customer.java
Labels: enhancement, Individual, mandatory

#719 feat(Student3): Task161-CreateAppropiateIndicesForYourEntitiesIfRequired.
  src/main/java/acme/entities/activityLog/ActivityLog.java
  src/main/java/acme/entities/flightAssignment/FlightAssignment.java
Labels: enhancement, Individual, mandatory

#721 feat(Student3):Task162
  src/test/resources/flightCrewMember/flightAssignment/create.hack
Labels: enhancement, Individual, mandatory

#722 Task 188 modification of csvs
  src/main/resources/WEB-INF/data/sample/aircraft.csv
  src/main/resources/WEB-INF/data/sample/airline.csv
  src/main/resources/WEB-INF/data/sample/airport.csv
  src/main/resources/WEB-INF/data/sample/flight.csv
  src/main/resources/WEB-INF/data/sample/leg.csv
Labels: documentation, enhancement, Individual
